#!/bin/bash

sudo apt-get install build-essential libgmp-dev libmpfr-dev libmpc-dev

wget http://ftp.gnu.org/gnu/binutils/binutils-2.26.tar.bz2
wget http://mirrors.concertpass.com/gcc/releases/gcc-6.1.0/gcc-6.1.0.tar.bz2
wget http://download.savannah.gnu.org/releases/avr-libc/avr-libc-2.0.0.tar.bz2

tar xvfj binutils-*
tar xvfj gcc-*
tar xvfj avr-libc-*

sudo mkdir /usr/local/avr
sudo chown $USER /usr/local/avr

export PREFIX=/usr/local/avr
export PATH=$PATH:$PREFIX/bin

cd ~/binutils-*
mkdir obj-avr
cd obj-avr
../configure --prefix=$PREFIX --target=avr --disable-nls
make
make install

cd ~/gcc-*
mkdir obj-avr
cd obj-avr
../configure --prefix=$PREFIX --target=avr --enable-languages=c,c++ --disable-nls --disable-libssp --with-dwarf2
make
make install

cd ~/avr-*
./configure --prefix=$PREFIX --build=`./config.guess` --host=avr
make
make install

cd ~
rm *.tar.bz2

echo "It won't work until you enter: export PATH=$PATH:/usr/local/avr/bin"
